name: build and test:dev


on:
  workflow_call:
      secrets:
            SNYK_TOKEN:
                required: true
 
  pull_request:
    branches: 
      - 'development'
  push:
    branches:
      - 'development'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: install packages with yarn
        run: yarn install
      - name: Build
        run: npm run build

  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    steps:
      - uses: actions/checkout@master
      - name: Use Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install packages with yarn
        run: yarn install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
 
        with:
          command: monitor
        
